import json
import subprocess
from typing import Any

import config
from testlink_custom_field import (
    ensure_automation_testdata_custom_field,
    upsert_testcase_custom_field_value,
)


def log_info(message: str) -> None:
    print(f"[INFO] {message}")


def log_success(message: str) -> None:
    print(f"[SUCCESS] {message}")


def log_error(message: str) -> None:
    print(f"[ERROR] {message}")


def _normalize_testcase_key(value: str) -> str:
    return " ".join(str(value or "").strip().lower().split())


def _obsolete_preconditions(note: str = "") -> str:
    message = (
        f"{config.TESTLINK_OBSOLETE_TAG} This testcase is no longer part of the latest "
        "requirement/design generated set."
    )
    if note:
        message += f" {note.strip()}"
    return message.strip()


def _active_preconditions() -> str:
    return "Generated by automation AI pipeline. Test data is stored in a TestLink custom field."


def _is_obsolete_testcase(raw_testcase: dict[str, Any]) -> bool:
    haystack = " ".join(
        [
            str(raw_testcase.get("preconditions", "")),
            str(raw_testcase.get("summary", "")),
        ]
    )
    return config.TESTLINK_OBSOLETE_TAG.lower() in haystack.lower()


def _require_testlink_config() -> bool:
    missing = []
    if not config.DEV_KEY:
        missing.append("DEV_KEY or TESTLINK_DEV_KEY")
    if not config.PROJECT_ID:
        missing.append("PROJECT_ID or TESTLINK_PROJECT_ID")
    if not config.SUITE_ID:
        missing.append("SUITE_ID or TESTLINK_SUITE_ID")

    if missing:
        log_error(
            "Skipping TestLink upload. Missing configuration: " + ", ".join(missing)
        )
        return False
    return True


def _format_steps(testcase: dict[str, Any]) -> list[dict[str, str]]:
    steps = []
    for order, step in enumerate(testcase.get("steps", []), start=1):
        steps.append(
            {
                "step_number": order,
                "actions": str(step.get("actions", "")),
                "expected_results": str(step.get("expected_results", "")),
                "execution_type": "1",
            }
        )
    return steps


def _find_testcases_by_name(client, testcase_name: str) -> list[dict[str, Any]]:
    suite_testcases = client.getTestCasesForTestSuite(
        testsuiteid=config.SUITE_ID,
        deep=True,
        details="full",
    )
    return [
        testcase
        for testcase in suite_testcases
        if isinstance(testcase, dict) and testcase.get("name") == testcase_name
    ]


def _get_suite_testcases(client) -> list[dict[str, Any]]:
    suite_testcases = client.getTestCasesForTestSuite(
        testsuiteid=config.SUITE_ID,
        deep=True,
        details="full",
    )
    return [testcase for testcase in suite_testcases if isinstance(testcase, dict)]


def _response_has_error(response: Any) -> bool:
    return isinstance(response, list) and response and response[0].get("status") is False


def _latest_testcase(matching_testcases: list[dict[str, Any]]) -> dict[str, Any] | None:
    if not matching_testcases:
        return None
    return max(
        matching_testcases,
        key=lambda testcase: (
            int(testcase.get("id", 0) or 0),
            int(testcase.get("version", 0) or 0),
        ),
    )


def _upsert_testcase_in_testlink(client, testcase: dict[str, Any]) -> bool:
    existing = _latest_testcase(_find_testcases_by_name(client, str(testcase["name"])))
    common_payload = {
        "testcasename": str(testcase["name"]),
        "summary": str(testcase.get("summary", "")),
        "steps": _format_steps(testcase),
        "preconditions": _active_preconditions(),
        "importance": 2,
        "executiontype": 1,
    }

    if existing and config.REUSE_EXISTING_TESTLINK_CASES:
        external_id = existing.get("external_id")
        if not external_id:
            log_error(f"Existing TestLink testcase has no external_id: {testcase['name']}")
            return False
        response = client.updateTestCase(
            testcaseexternalid=str(external_id),
            version=int(existing.get("version", 1) or 1),
            user=config.TESTLINK_AUTHOR_LOGIN,
            **common_payload,
        )
        if _response_has_error(response):
            log_error(f"TestLink rejected update for '{testcase['name']}': {response}")
            return False
        log_success(f"Updated existing TestLink testcase: {testcase['name']}")
        return True

    response = client.createTestCase(
        testsuiteid=config.SUITE_ID,
        testprojectid=config.PROJECT_ID,
        authorlogin=config.TESTLINK_AUTHOR_LOGIN,
        **common_payload,
    )
    if _response_has_error(response):
        log_error(f"TestLink rejected '{testcase['name']}': {response}")
        return False
    log_success(f"Created new TestLink testcase: {testcase['name']}")
    return True


def _update_testdata_custom_field(client, testcase: dict[str, Any], field_id: int) -> bool:
    matching_testcases = _find_testcases_by_name(client, str(testcase["name"]))
    if not matching_testcases:
        log_error(f"Could not find TestLink testcase after upload: {testcase['name']}")
        return False

    testdata_json = json.dumps(testcase.get("testdata", {}), separators=(",", ":"), sort_keys=True)
    for matching_testcase in matching_testcases:
        upsert_testcase_custom_field_value(
            field_id=field_id,
            testcase_version_id=int(matching_testcase["tcversion_id"]),
            value=testdata_json,
        )
    return True


def _add_testcase_to_testplan(client, testcase: dict[str, Any]) -> None:
    if not config.TESTLINK_TESTPLAN_ID:
        return

    latest = _latest_testcase(_find_testcases_by_name(client, str(testcase["name"])))
    if not latest:
        log_error(f"Could not assign missing testcase to Test Plan: {testcase['name']}")
        return

    external_id = latest.get("external_id")
    if not external_id:
        log_error(f"Could not assign testcase without external_id to Test Plan: {testcase['name']}")
        return

    try:
        response = client.addTestCaseToTestPlan(
            testprojectid=config.PROJECT_ID,
            testplanid=config.TESTLINK_TESTPLAN_ID,
            testcaseexternalid=str(external_id),
            version=int(latest.get("version", 1) or 1),
            overwrite=True,
        )
        if _response_has_error(response):
            log_error(f"TestLink rejected Test Plan assignment for '{testcase['name']}': {response}")
        else:
            log_success(f"Assigned testcase to Test Plan {config.TESTLINK_TESTPLAN_ID}: {testcase['name']}")
    except Exception as exc:
        message = str(exc)
        if "already" in message.lower() or "duplicate" in message.lower():
            log_info(f"Testcase already assigned to Test Plan {config.TESTLINK_TESTPLAN_ID}: {testcase['name']}")
        else:
            log_error(f"Failed to assign testcase '{testcase['name']}' to Test Plan via API: {exc}")

    try:
        _ensure_tcversion_in_testplan(int(latest.get("tcversion_id", 0) or 0))
        log_success(f"Verified testcase version in Test Plan {config.TESTLINK_TESTPLAN_ID}: {testcase['name']}")
    except Exception as exc:
        log_error(f"Failed to verify testcase version in Test Plan for '{testcase['name']}': {exc}")


def _ensure_tcversion_in_testplan(tcversion_id: int) -> None:
    if not tcversion_id or not config.TESTLINK_TESTPLAN_ID:
        return
    sql = (
        "INSERT IGNORE INTO testplan_tcversions "
        "(testplan_id, tcversion_id, node_order, urgency, platform_id, author_id) "
        f"VALUES ({int(config.TESTLINK_TESTPLAN_ID)}, {int(tcversion_id)}, 1, 2, 0, 1);"
    )
    command = [
        config.MYSQL_EXE,
        f"-h{config.TESTLINK_DB_HOST}",
        f"-u{config.TESTLINK_DB_USER}",
        f"-p{config.TESTLINK_DB_PASSWORD}",
        config.TESTLINK_DB_NAME,
        "-e",
        sql,
    ]
    subprocess.run(command, check=True, capture_output=True, text=True)


def _mark_testcase_obsolete(client, raw_testcase: dict[str, Any]) -> bool:
    external_id = raw_testcase.get("external_id")
    version = int(raw_testcase.get("version", 1) or 1)
    testcase_name = str(raw_testcase.get("name") or raw_testcase.get("testcase_name") or external_id or "")
    if not external_id:
        log_error(f"Could not mark testcase obsolete because external_id is missing: {testcase_name}")
        return False

    response = client.updateTestCase(
        testcaseexternalid=str(external_id),
        version=version,
        user=config.TESTLINK_AUTHOR_LOGIN,
        testcasename=testcase_name,
        summary=str(raw_testcase.get("summary", "")),
        steps=[
            {
                "step_number": int(step.get("step_number", index) or index),
                "actions": str(step.get("actions", "")),
                "expected_results": str(step.get("expected_results", "")),
                "execution_type": str(step.get("execution_type", "1")),
            }
            for index, step in enumerate(raw_testcase.get("steps", []) or [], start=1)
            if isinstance(step, dict)
        ],
        preconditions=_obsolete_preconditions(),
        importance=int(raw_testcase.get("importance", 2) or 2),
        executiontype=int(raw_testcase.get("execution_type", 1) or 1),
    )
    if _response_has_error(response):
        log_error(f"TestLink rejected obsolete marking for '{testcase_name}': {response}")
        return False

    log_success(f"Marked obsolete TestLink testcase: {testcase_name}")
    return True


def _mark_obsolete_testcases(client, generated_testcases: list[dict[str, Any]]) -> int:
    if not config.DEACTIVATE_OBSOLETE_TESTCASES:
        return 0

    generated_keys = {
        _normalize_testcase_key(testcase.get("name", ""))
        for testcase in generated_testcases
        if testcase.get("name")
    }
    if not generated_keys:
        return 0

    suite_testcases = _get_suite_testcases(client)
    latest_by_key: dict[str, dict[str, Any]] = {}
    for raw_testcase in suite_testcases:
        key = _normalize_testcase_key(
            raw_testcase.get("name") or raw_testcase.get("testcase_name") or ""
        )
        if not key:
            continue
        existing = latest_by_key.get(key)
        if existing is None or int(raw_testcase.get("id", 0) or 0) > int(existing.get("id", 0) or 0):
            latest_by_key[key] = raw_testcase

    obsolete_count = 0
    for key, raw_testcase in latest_by_key.items():
        if key in generated_keys:
            continue
        if _is_obsolete_testcase(raw_testcase):
            continue
        if _mark_testcase_obsolete(client, raw_testcase):
            obsolete_count += 1

    if obsolete_count:
        log_info(
            f"Marked {obsolete_count} obsolete testcase(s) so only the latest requirement/design set will execute."
        )
    return obsolete_count


def upload_testcases(testcases: list[dict[str, Any]]) -> dict[str, int]:
    metrics = {"uploaded": 0, "requested": len(testcases), "obsolete_marked": 0}
    if not testcases:
        log_error("Skipping TestLink upload because there are no testcases.")
        return metrics

    if not _require_testlink_config():
        return metrics

    field_id = ensure_automation_testdata_custom_field()

    try:
        import testlink

        client = testlink.TestlinkAPIClient(config.TESTLINK_URL, config.DEV_KEY)
    except Exception as exc:
        log_error(f"Unable to connect to TestLink API: {exc}")
        return metrics

    uploaded_count = 0
    for testcase in testcases:
        try:
            if not _upsert_testcase_in_testlink(client, testcase):
                continue
            if not _update_testdata_custom_field(client, testcase, field_id):
                continue
            _add_testcase_to_testplan(client, testcase)
            uploaded_count += 1
            log_success(f"Uploaded custom test data to TestLink: {testcase['name']}")
        except Exception as exc:
            log_error(f"Failed to upload testcase '{testcase.get('name', 'unknown')}': {exc}")

    try:
        metrics["obsolete_marked"] = _mark_obsolete_testcases(client, testcases)
    except Exception as exc:
        log_error(f"Failed to synchronize obsolete TestLink testcases: {exc}")

    metrics["uploaded"] = uploaded_count
    log_info(f"TestLink upload completed. Upserted {uploaded_count}/{len(testcases)} without creating duplicates.")
    return metrics
